# Generated by Django 4.2.4 on 2024-06-20 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminid', models.AutoField(primary_key=True, serialize=False)),
                ('adminemail', models.EmailField(max_length=254)),
                ('adminname', models.CharField(max_length=50)),
                ('adminuser', models.CharField(max_length=30)),
                ('adminpassword', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookingid', models.AutoField(primary_key=True, serialize=False)),
                ('equipment', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('memberid', models.AutoField(primary_key=True, serialize=False)),
                ('memberemail', models.EmailField(max_length=254)),
                ('membername', models.CharField(max_length=50)),
                ('memberpassword', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('registrationid', models.AutoField(primary_key=True, serialize=False)),
                ('studclass', models.CharField(max_length=30)),
                ('studphone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userfullname', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=30)),
                ('useremail', models.EmailField(max_length=254)),
                ('userphone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('username', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=225)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SEDAYA_IMS.user')),
            ],
        ),
    ]
